"""empty message

Revision ID: 4f4b4bdafe7c
Revises: 
Create Date: 2019-07-14 14:55:09.549547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4b4bdafe7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_index('key', table_name='coupon')
    op.create_unique_constraint(None, 'coupon', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coupon', type_='unique')
    op.create_index('key', 'coupon', ['key'], unique=True)
    op.drop_column('coupon', 'name')
    # ### end Alembic commands ###
