"""empty message

Revision ID: 8608ba461510
Revises: 4f4b4bdafe7c
Create Date: 2019-07-14 16:43:26.826575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8608ba461510'
down_revision = '4f4b4bdafe7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon', 'used')
    # ### end Alembic commands ###
