"""empty message

Revision ID: 9417114932c2
Revises: 8608ba461510
Create Date: 2019-07-14 18:17:23.785872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9417114932c2'
down_revision = '8608ba461510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_name', table_name='coupon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_name', 'coupon', ['user_name'], unique=True)
    # ### end Alembic commands ###
